### PR TITLE
Fix setup.py and some other bugs, add a new background image, change how background images are handled.

### PR DESCRIPTION
**Pull request by BookOwl**
1. I got setup.py to work! To install, run `python setup.py bdist_wheel`
   and then run `pip install path`, where path is the final path of the
   .whl file (should be in dist/)
2. I fixed a bug in slither where it couldn't find the snakey.png image.
3. I made a better background picture for bgTest.py
4. I made slither scale background images to fill the entire background.
5. I updated .gitignore to ignore the nppBackup folder (created by
   notepad++) and Thumbs.db (mad by Windows)

### CODE REVIEW

**Comment by Tymewalk** [comment]
Do you think you can make an 800x600 version of that background?
Other than that, looks good!

**Comment by BookOwl** [comment]
At first I thought that the slither stage was 480 by 360, so that is what resolution I used. I make  new image.

**Comment by BookOwl** [comment]
I created a higher res bg image.

**Comment by BookOwl** [comment]
I'm going to make a new branch for any other features I want to add.

**Comment by Tymewalk** [comment]
OK. In the meantime I'll merge this, it looks good.

**Comment by BookOwl** [comment]
Great!

**Pull request merged**
