### PR TITLE
Add #10

### PR DESCRIPTION
**Pull request by BookOwl**
This pull request implements issue #10 (Automatically blit the screen, handle events, and pause)
I added an example using the new API

### CODE REVIEW

**Comment by BookOwl** [comment]
@Tymewalk

**Comment by Tymewalk** [comment]
Looks good to me, I'm resolving any conflicts now.

**Comment by Tymewalk** [comment]
Done! Thanks for helping!

**Comment by BookOwl** [comment]
@Tymewalk No problem!

**Pull request merged**
