### PR TITLE
Remove set, get, and changeBy functions

### PR DESCRIPTION
**Pull request by Tymewalk**
Removes set, changeBy, and get functions, except for:
- Costumes, since those are handled specially
- goTo (although this may also be removed)

For fixing #30.

### CODE REVIEW

**Comment by BookOwl** [comment]
I think that we should keep goTo (but can we please rename it goto?)

**Comment by Tymewalk** [comment]
@BookOwl Sure.

**Comment by BookOwl** [comment]
Ok. I just have always seen it spelled that way.

**Comment by BookOwl** [comment]
Should we remove the get/set functions from Stage?

**Comment by Tymewalk** [comment]
@BookOwl Which ones?

**Comment by Tymewalk** [comment]
Oh, never mind, you mean `setColor` and `getCostumeNumber` and `getCostumeName`.
Sure, I'll remove those.

The only thing that has to stay is costumes because those get handled specially with a bunch of magic I wrote a couple of weeks ago.

**Comment by BookOwl** [comment]
> Oh, never mind, you mean setColor and getCostumeNumber and getCostumeName.
> Sure, I'll remove those.

Great!

> The only thing that has to stay is costumes because those get handled specially with a bunch of magic I wrote a couple of weeks ago.

We actually could get rid of those by using properties.

**Comment by Tymewalk** [comment]
> We could actually get rid of those by using properties.

OK. But for now, I'm going to merge this to master and make a new pull request for that - I kinda mucked up this branch using the command-line

**Comment by BookOwl** [comment]
Sounds good to me!

**Pull request merged**
