### PR TITLE
Fix #76

### LINKED ISSUE #76: basicTest.py doesn't work in Python2
The circling sprite in the middle has the wrong costume. I did some testing, and it's been that way since commit  db54b1d (or version 0.2.1). I couldn't get 0.2.0 to work in python2.
The test does work in 0.2.1 on python3

### PR DESCRIPTION
**Pull request by Tymewalk**
Will fix #76.

### CODE REVIEW

**Comment by BookOwl** [comment]
Just remove the prints and rename the vars and we should be able to merge.

**Comment by Tymewalk** [comment]
@BookOwl Yep, the inheritance worked!

**Comment by BookOwl** [comment]
Great!

**Comment by BookOwl** [comment]
Is this ready to merge?

**Comment by Tymewalk** [comment]
@BookOwl No. Still need to rename vars with their `_var` equivalents

But then I'll test and then yes.

**Comment by Tymewalk** [comment]
Just fixed it. All variables now have underscores where they should be, preventing any other glitches. `basicTest.py` still works, so everything's fine :confetti_ball:

**Pull request merged**
