### PR TITLE
Move code from __init__.py to slither.py

### PR DESCRIPTION
**Pull request by CosmicWebServices**
See #68 

Not tested.

### CODE REVIEW

**Comment by skistaddy** [comment]
+1

**Comment by CosmicWebServices** [comment]
Thanks!

**Comment by skistaddy** [comment]
:D

**Comment by BookOwl** [comment]
I don't like this, it means that instead of just importing slither, users have to do `from slither import slither`, which just seems weird.

**Comment by CosmicWebServices** [comment]
or `from slither import *`

**Comment by BookOwl** [comment]
But that's considered bad practice. and we really shouldn't be encouraging that.
What's wrong with having everything in the **init**.py

**Comment by CosmicWebServices** [comment]
I just realised we can put `import slither` in `__init__.py`

**Comment by ghost** [comment]
But why do we need this? And besides It's not like we have optional modules for slither.

**Comment by skistaddy** [comment]
@CosmicWebServices +1

**Comment by emmatyping** [comment]
> But why do we need this? And besides It's not like we have optional modules for slither.

Python style dictates that as little operational code should go in an`__init__.py` file as possible. I believe the importing of slither.py, as @Omegabyte suggested is often the practice used.

**Comment by BookOwl** [comment]
I think that @Tymewalk needs to make this decision.

**Comment by CosmicWebServices** [comment]
OK

**Comment by Tymewalk** [comment]
I'm confused here.

So users will have to use `from slither import *`? Why not have a `from slither import *` in `__init__.py` and then use `import slither` like normal? Or just keeping things the way they are?

@ethanhs Where does it say that? I've never heard that rule, nor seen it used anywhere.

**Comment by CosmicWebServices** [comment]
no it will be the same as now

**Comment by Tymewalk** [comment]
@CosmicWebServices Oh, OK. But the code doesn't look that way.

**Comment by CosmicWebServices** [comment]
Well I made it in the format that `__init__.py` should be in but I would still test it...

**Comment by emmatyping** [comment]
I might have mis-spoken. What I really mean when I say "as little operational code as possible" is to say that the `__init__.py` should contain _setup code_. 

> The purpose of the **init**.py files is to include optional initialization code that runs as different levels of a package are encountered.

and 

> More often that not, it’s fine to just leave the **init**.py files empty. However, there are certain situations where they might include code. For example, an **init**.py file can be used to automatically load submodules

[src](http://chimera.labs.oreilly.com/books/1230000000393/ch10.html#_solution_169)

Also:

> For a simple package, you might be tempted to throw utility methods, factories and exceptions into your **init**.py. Don’t.
> A well-formed **init**.py serves one very important purpose: to import from sub-modules.

[src](https://axialcorps.com/2013/08/29/5-simple-rules-for-building-great-python-packages/)

One more:

> **init**.py can be an empty file but it is often used to perform setup needed for the package(import things, load things into path, etc).

[src](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html)

Based on these, I would recommend `from . import slither` or simply `import slither` and move all the code to `slither.py`

**Comment by skistaddy** [comment]
@ethanhs +1

**Comment by Tymewalk** [comment]
@ethanhs Oh, OK. That makes more sense.

Based on that I think we should restructure **init**.py so users can still use `import slither`, but so the code is in a separate file.

**Comment by CosmicWebServices** [comment]
yeah that makes more sense

**Comment by Tymewalk** [comment]
I'm going to close this pull request as it doesn't do this which is the eventual goal (unless you'd like to update it so it does do this, @CosmicWebServices).

**Comment by CosmicWebServices** [comment]
u do it

**Comment by Tymewalk** [comment]
@CosmicWebServices I can't since I don't have write access to your repo.

If you'd like I can close this and just make a new PR.

**Comment by CosmicWebServices** [comment]
PR?

**Comment by skistaddy** [comment]
@CosmicWebServices Pull Request

**Comment by CosmicWebServices** [comment]
What is in the new pull request???

**Comment by Tymewalk** [comment]
@CosmicWebServices I'd rewrite the current version of Slither to work so **init**.py only contains an import and users can still use `import slither`.

**Comment by CosmicWebServices** [comment]
OK I will do that tommarow

**Comment by Tymewalk** [comment]
@CosmicWebServices OK then.

This PR is being left open since @CosmicWebServices is working on updating it.

**Comment by CosmicWebServices** [comment]
Updated it!

**Comment by emmatyping** [comment]
I'm going to recommend that you do `from . import slither`, as that will not cause issues with namespaces getting imported twice etc.

Just an idea.

**Comment by CosmicWebServices** [comment]
Good Idea Fixing that

**Comment by CosmicWebServices** [comment]
Done

**Comment by Tymewalk** [comment]
Tests can still use `import slither` correctly, right?

**Comment by BookOwl** [comment]
I think that for this change to be accepted, all the tests must work perfectly without making any changes.

**Comment by CosmicWebServices** [comment]
@BookOwl I agree

**Comment by BookOwl** [comment]
@CosmicWebServices, what progress have you made?

**Comment by CosmicWebServices** [comment]
It is done

**Comment by BookOwl** [comment]
OK, @Tymewalk can look it over one more time and then we can merge.

**Comment by Tymewalk** [comment]
@BookOwl @CosmicWebServices I'm cloning that repo now to test.

**Comment by Tymewalk** [comment]
Used `import slither` in basicTest.py.

```
Traceback (most recent call last):
  File "slither/tests/basicTest.py", line 3, in <module>
    snakey = slither.Sprite()
AttributeError: 'module' object has no attribute 'Sprite'
```

**Comment by BookOwl** [comment]
@Tymewalk, I think that the `__init__.py` file needs to be changed to `from .slither import *`

**Comment by BookOwl** [comment]
Yep, that fixes it.

**Comment by BookOwl** [comment]
@CosmicWebServices, can you add that fix?
Also, the tests need to be changed back to `import slither`, not `from slither import *`

**Comment by CosmicWebServices** [comment]
Got it...

**Comment by BookOwl** [comment]
I just tested it and it seems to work, but you need to revert the tests' import back to `import slither`
Other than that, it looks great! Thanks for putting in all this work.

**Comment by CosmicWebServices** [comment]
I forgot about the tests I will do that soon (tomorrow probably)

**Comment by BookOwl** [comment]
@CosmicWebServices, when do you think that you will finish this?

**Comment by CosmicWebServices** [comment]
I forgot doing it now

**Comment by CosmicWebServices** [comment]
Done sorry it took so long!

**Comment by BookOwl** [comment]
I just tested it, and it seems to work, so merging.

**Comment by CosmicWebServices** [comment]
Nice!

**Pull request merged**
