### PR TITLE
Add isTouching() method

### PR DESCRIPTION
**Pull request by Tymewalk**
Works as follows:

```
Sprite.isTouching(Sprite)
```

Uses the `colliderect` method.

### CODE REVIEW

**Comment by BookOwl** [comment]
Looks good. Add a test before you merge it.

**Comment by Tymewalk** [comment]
Strange... the test only prints "1".

**Comment by Tymewalk** [comment]
The current test prints this:

```
Touching!
<rect(0, 0, 200, 169)>
<rect(0, 0, 200, 169)>
```

So I'm not sure `colliderect` is working properly. Either that or I messed something up :package:

**Comment by Tymewalk** [comment]
@BookOwl Some testing later, I find that it keeps returning a value of `1` <s>(or printing it, anyways)</s>.

I thought `colliderect` returned a boolean...?

**Comment by Tymewalk** [comment]
Never mind that.

I found the problem, it's that the `rect` in `currentCostume` never actually gets updated. `Sprite.xpos` and `Sprite.ypos` control it all.

**Comment by Tymewalk** [comment]
I used a method similar to the `blit` function. The function works as expected now.
@BookOwl can you look it over one last time to make sure it looks good?

**Comment by BookOwl** [comment]
I'm not sure, but doesn't assigning to a rect's properties move it?
I haven't gotten pygame set up on my computer, so I can't test it (yet)

**Comment by Tymewalk** [comment]
@BookOwl I'm not sure, I haven't ever bothered to test. :tongue: 
However, when checking collisions, I create new `rect`s that get modified with the properties. They're immediately discarded afterwards.

EDIT: By the way, when I run the test everything works fine. It looks exactly the same as when I don't check for touching.

**Comment by BookOwl** [comment]
The isTouchingTest.py file uses python2 style prints...

**Comment by BookOwl** [comment]
I fixed the print statements. Other than that, the test looks good. Merging

**Pull request merged**
