### PR TITLE
Implement #48

### PR DESCRIPTION
**Pull request by BookOwl**
Added a moveSteps method to the Sprite class, which implements #48
I also added a new test for this feature, and changed .gitignore to ignore Thumbs.db files (created by Windows)

### CODE REVIEW

**Comment by BookOwl** [comment]
I also fixed a bug in the way costumes are displayed when rotated

**Comment by BookOwl** [comment]
@Tymewalk

**Comment by Tymewalk** [comment]
Looks good to me.
Any reason Thumbs.db is in .gitignore now, though?

**Comment by BookOwl** [comment]
Windows automatically creates it. I all that I know about it is that it has do with pictures

**Comment by Tymewalk** [comment]
@BookOwl Weird.
Anyways, I was just curious, the rest looked fine to me.

**Pull request merged**
