### PR TITLE
Create general.md

### PR DESCRIPTION
**Pull request by skistaddy**
This will be the place we can add links to the other Doc Files.

### CODE REVIEW

**Comment by CosmicWebServices** [comment]
I think this is covered in  `readme.md`

**Comment by skistaddy** [comment]
@CosmicWebServices Nope, this will be for the many more doc files.

**Comment by CosmicWebServices** [comment]
OK

**Comment by skistaddy** [comment]
:) (Sorry, if that sounded kinda stern. XD)

**Comment by CosmicWebServices** [comment]
np

**Comment by Tymewalk** [comment]
Sounds good. We can create a small description of the docs in README.md and cover the rest here.

@BookOwl @Omegabyte What are your thoughts?

**Comment by BookOwl** [comment]
@Tymewalk, I think that we should be using [MkDocs](http://www.mkdocs.org/#getting-started) for our documentation, since it will let us write our documentation in markdown and let us put the docs on readthedocs.

**Comment by BookOwl** [comment]
Since #71 was merged, I don't think this is necessary.

**Comment by skistaddy** [comment]
OK!

**Pull request closed without merging**
