### PR TITLE
IMPORTANT: Added help folder

### PR DESCRIPTION
**Pull request by ghost**
After a day of work it's finally done! The help folder contains a help page (.html web page) with a python launcher. Please correct my work if I made spelling mistakes.

### CODE REVIEW

**Comment by ghost** [comment]
The help page displays a simple getting started script and then shows a table with each command and a brief description.

**Comment by Tymewalk** [comment]
Are those standard modules? I don't want people having to install a bunch of extra stuff just to use the help page.

Other than that, it looks good!

**Comment by Tymewalk** [comment]
Also, I'm adding new functions in, but don't worry about updating your docs - I'll update everything once I merge it.

**Comment by BookOwl** [comment]
Yes, it just uses the standard library

**Comment by Tymewalk** [comment]
@BookOwl OK then. I just figure if this is going up on PyPi I want to have everything set up properly.

**Comment by ghost** [comment]
This uses out of the box modules, I used try so it would attempt to use python 2 modules but if not available use python 3 modules.

**Comment by Tymewalk** [comment]
Looks good to me!

I'm going to merge it, and add you as a collaborator so you can help with the new format's documentation.

**Pull request merged**
