### PR TITLE
Implement #62

### PR DESCRIPTION
**Pull request by Tymewalk**
When done, will implement #62.

### CODE REVIEW

**Comment by Tymewalk** [comment]
That other Tymewalk is me. I entered the e-mail wrong.

**Comment by Tymewalk** [comment]
Strangely, the text does not display. It probably has to do with the background fill.

**Comment by Tymewalk** [comment]
Testing again, text properly shows, but it flickers in and out.

**Comment by Tymewalk** [comment]
Yep, that was it. The problem was both `pygame.display.flip()`s fighting. Replacing it with one `display.flip()` at the end fixed it.

**Comment by BookOwl** [comment]
Great! 😄

**Pull request merged**
