### PR TITLE
60 FPS

### PR DESCRIPTION
**Pull request by Tymewalk**
60 FPS is pretty standard.

I'm making this a pull request so people can discuss it here.

### CODE REVIEW

**Comment by BookOwl** [comment]
I just did 30 FPS because that's what Scratch does.

**Comment by Tymewalk** [comment]
@BookOwl Oh, OK.
I personally think Slither should take advantage of the fact it's not written in Flash, allowing it to perform much better than Scratch in certain cases. What do you think?

**Comment by BookOwl** [comment]
How about we make the default 60, but allow it to be changed and also mentioning that Scratch runs at 30 FPS?

**Comment by Tymewalk** [comment]
@BookOwl OK. How about something like this:

```
def setFPS(fps):
    '''Set the FPS of the project. Default is 60, and Scratch runs at 30.'''
    projectFPS = fps # projectFPS is the FPS that the main loop uses
```

**Comment by BookOwl** [comment]
Sounds good to me!

**Comment by Tymewalk** [comment]
@BookOwl OK, controlling FPS is now set up. Anything else that should be fixed before I merge?

**Comment by BookOwl** [comment]
I don't think so.

**Comment by Tymewalk** [comment]
@BookOwl All right then.
If there's nothing else, I'll go ahead and merge this so I can get to work on #17 (and then maybe #16 and #13.)

**Pull request merged**
